#!/bin/bash

numOfRow=$( cat $1 | wc -l )
awk -v nOR=$numOfRow '{ rest=nOR-NR; for(k=1;k<=2;k++){printf "%f",$1; for(i=1;i<=NR;i++){printf " ";}; printf "%f",$1; for(i=1;i<=rest;i++){printf " ";}; printf "\n";} }' $1 | sed 's/ /\,/g' | nl -n rz | sed 's/\t/\,/'> $1_



#example
#1.2
#2.5
#-2
#-5
